import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "./globals.css";
import { Navigation } from '@/entities/navigation/ui';
import { ThemeProvider } from '@/entities/providers/themeProvider';
import { Toaster } from '@/shared/components/ui/toaster';


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400",
  style: "normal",
  display: "swap", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} font-poppins antialiased `}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navigation />
          <Toaster />
          <main className='max-w-8xl mx-auto py-4 px-4'>
            {children}
          </main>          
        </ThemeProvider>        
      </body>
    </html>
  );
}
