import { ThemeProvider } from '@/entities/providers/themeProvider';
import "../globals.css";
import { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { Navigation } from '@/entities/navigation/ui';
import { Footer } from '@/entities/footer/ui';

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400",
  style: "normal",
  display: "swap", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} font-poppins antialiased flex min-h-screen flex-col w-full justify-center bg-gradient-to-b from-slate-50 to-white`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navigation isHome={true}/>
          <main className='container mx-auto px-4 py-4'>
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
