import type { Metadata } from "next";
import {  Poppins } from "next/font/google";
import "../globals.css";
import { Navigation } from '@/entities/navigation/ui';
import { ThemeProvider } from '@/entities/providers/themeProvider';
import { Toaster } from '@/shared/components/ui/toaster';
import { Footer } from '@/entities/footer/ui';


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400",
  style: "normal",
  display: "swap", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} font-poppins antialiased flex min-h-screen flex-col w-full bg-gradient-to-b from-slate-50 to-white`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navigation isHome={false}/>
          <Toaster />
          <main className='max-w-8xl mx-auto py-4 px-4 flex-1 w-full'>
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
